Repository cburstedde/libsc, pull requests merged in 2025-03, with the labels that each got.

#217 nary-payload: set payload in notify_nary for mpisize==1
  src/sc_notify.c
  src/sc_notify.h
Labels: bug, enhancement

#219 scda: Rename options to params and add logging level
  src/sc_scda.c
  src/sc_scda.h
  test/test_scda.c
Labels: enhancement

#218 Feature distro
  cmake/config.cmake
  cmake/pkgconf.pc.in
  cmake/sc_config.h.in
  config/sc_autotools.pc.in
  config/sc_memalign.m4
  configure.ac
  src/sc.c
  src/sc.h
  test/CMakeLists.txt
  test/test_helpers.c
Labels: enhancement

#220 scda: Warn about future API change
  doc/release_notes.txt
  src/sc_scda.h
Labels: documentation

#221 Feature visibility
  doc/release_notes.txt
  src/sc.h
Labels: enhancement
